[package]
name = "pimtron"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
console_error_panic_hook = "0.1.7"
gray_matter = "0.3.2"
include_dir = "0.7.4"
leptos = { version = "0.8.14", features = ["csr"] }
leptos_meta = "0.8.5"
leptos_router = "0.8.10"
pulldown-cmark = "0.13.0"
serde = { version = "1.0.228", features = ["derive"] }
stylance = "0.7.4"
web-sys = { version = "0.3", features = ["Document", "Element", "Window", "Node", "HtmlCanvasElement", "WebGlRenderingContext", "Navigator", "Gpu"] }
wasm-bindgen = "0.2"
js-sys = "0.3"
wasm-bindgen-futures = "0.4.56"

# Optimize dependencies even in dev builds to reduce binary size and memory usage
[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
