# Source - https://stackoverflow.com/a
# Posted by Chris
# Retrieved 2025-11-28, License - CC BY-SA 4.0

[build]
no_sri = true

[[hooks]]
stage = "pre_build"
command = "stylance"
command_arguments = [".", "--output-file", "index.css"]

[watch]
ignore = ["index.css"]
