# Source - https://stackoverflow.com/a
# Posted by Chris
# Retrieved 2025-11-28, License - CC BY-SA 4.0

[build]
no_sri = true

[[hooks]]
stage = "pre_build"
command = "stylance"
command_arguments = [".", "--output-file", "index.css"]

[[hooks]]
stage = "pre_build"
command = "cargo"
command_arguments = ["run", "--bin", "gen_posts"]

[watch]
ignore = ["index.css", "generated_posts"]

[[copy]]
source = "generated_posts"
target = "posts"
